# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

minecraft_version=26.2
yarn_mappings=1.21.11+build.6
loader_version=0.19.3

mod_version=1.0
maven_group=me.x3r0day
archives_base_name=XUtil

fabric_version=0.156.0+26.2

minecraftauth_version=5.0.2
lenni_httpclient_version=1.9.2
lenni_gson_version=1.9.2
